### ISSUE TITLE
Any updated for this to be completed?

### ISSUE THREAD

**Issue by KestasVenslauskas** [ou2s/react-native-gemius#1]
Basically the title

**Comment by ou2s** [comment]
What do you mean by "completed"? What functionality do you need? This library is not maintained anymore and it only covers session and page view tracking.

PR is welcomed if you want to add functionality.

BTW, beware, if you use CodePush, the session measurement won't work as expected.

**Comment by KestasVenslauskas** [comment]
Will try to play around a little.
